import Foundation
import SwiftData

@Model
final class Caregiver {
    @Attribute(.unique) var id: UUID
    var displayName: String
    @Attribute(.externalStorage) var photoData: Data?
    var role: CaregiverRole
    var supabaseUserID: String?     // nil for anonymous / not yet synced
    var isCurrentDevice: Bool       // true for the logged-in user on this device
    var joinedAt: Date
    var syncStatus: SyncStatus
    var remoteID: String?
    var updatedAt: Date

    init(id: UUID = UUID(), displayName: String, role: CaregiverRole = .admin, isCurrentDevice: Bool = false) {
        self.id = id
        self.displayName = displayName
        self.role = role
        self.isCurrentDevice = isCurrentDevice
        self.joinedAt = Date()
        self.syncStatus = .pending
        self.updatedAt = Date()
    }
}

enum CaregiverRole: String, Codable, CaseIterable {
    case admin      // full access: add/edit/delete babies and entries
    case caregiver  // can add/edit entries; cannot add/delete babies or manage caregivers
    case viewer     // read-only

    var displayName: String {
        switch self {
        case .admin: return "Admin"
        case .caregiver: return "Caregiver"
        case .viewer: return "Viewer"
        }
    }

    var description: String {
        switch self {
        case .admin: return "Full access including managing babies and caregivers"
        case .caregiver: return "Can log feedings, sleep, diapers, and health entries"
        case .viewer: return "Can view all entries but cannot add or edit"
        }
    }

    // Permission helpers — enforced in ViewModels and in Supabase RLS
    var canAddEntry: Bool { self == .admin || self == .caregiver }
    var canEditEntry: Bool { self == .admin || self == .caregiver }
    var canDeleteEntry: Bool { self == .admin }
    var canManageBabies: Bool { self == .admin }
    var canManageCaregivers: Bool { self == .admin }
}

// MARK: - Handoff Note

@Model
final class HandoffNote {
    @Attribute(.unique) var id: UUID
    var babyID: UUID
    var authorCaregiverID: UUID
    var text: String
    var isActive: Bool
    var createdAt: Date
    var syncStatus: SyncStatus
    var remoteID: String?

    init(babyID: UUID, authorCaregiverID: UUID, text: String) {
        self.id = UUID()
        self.babyID = babyID
        self.authorCaregiverID = authorCaregiverID
        self.text = text
        self.isActive = true
        self.createdAt = Date()
        self.syncStatus = .pending
    }
}

// MARK: - Family / Baby Access

/// Junction table: which caregivers have access to which babies
@Model
final class BabyAccess {
    @Attribute(.unique) var id: UUID
    var babyID: UUID
    var caregiverID: UUID
    var role: CaregiverRole
    var grantedAt: Date
    var syncStatus: SyncStatus
    var remoteID: String?

    init(babyID: UUID, caregiverID: UUID, role: CaregiverRole) {
        self.id = UUID()
        self.babyID = babyID
        self.caregiverID = caregiverID
        self.role = role
        self.grantedAt = Date()
        self.syncStatus = .pending
    }
}

// MARK: - Invite

/// Invite links generated by an admin. One-time use, expire after 7 days.
@Model
final class CaregiverInvite {
    @Attribute(.unique) var id: UUID
    var babyID: UUID
    var createdByID: UUID
    var role: CaregiverRole
    var code: String            // 8-char alphanumeric code
    var expiresAt: Date
    var usedAt: Date?
    var usedByID: UUID?
    var syncStatus: SyncStatus
    var remoteID: String?

    var isExpired: Bool { Date() > expiresAt }
    var isUsed: Bool { usedAt != nil }
    var isValid: Bool { !isExpired && !isUsed }

    init(babyID: UUID, createdByID: UUID, role: CaregiverRole) {
        self.id = UUID()
        self.babyID = babyID
        self.createdByID = createdByID
        self.role = role
        self.code = CaregiverInvite.generateCode()
        self.expiresAt = Calendar.current.date(byAdding: .day, value: 7, to: Date())!
        self.syncStatus = .pending
    }

    private static func generateCode() -> String {
        let chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"  // no ambiguous chars
        return String((0..<8).map { _ in chars.randomElement()! })
    }
}
